# Generated by Django 2.2.11 on 2020-03-26 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=255)),
                ('movieprice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('movieentrydate', models.DateField()),
                ('movieurl', models.URLField(blank=True, null=True)),
                ('moviedescription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('typedescription', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'movietypes',
                'db_table': 'movietype',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('reviewrating', models.SmallIntegerField()),
                ('reviewtext', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviereviewapp.Movie')),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='movietype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moviereviewapp.MovieType'),
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
